name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true

      matrix:
        os: [ubuntu-latest]
        pyv: ["3.9"]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pyv }}

    - name: Install dependencies
      run: |
        python -m pip install pytest
        python -m pip install -e ".[file]"

    - name: Test
      run: python -m pytest
